{% set name = "grpc-interceptor" %}
{% set version = "0.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/d5h-foss/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 382a2a1a18e40929f2ef635c06f16e32e6c2927293484368114cf1fd14aaa81a

build:
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - poetry-core >=1.0.0
  run:
    - python
    - grpcio >=1.49.1,<2.0.0
  run_constrained:
    - protobuf >=4.21.9

test:
  source_files:
    - tests
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests
  requires:
    - pip
    - python
    - pytest
    - protobuf >=4.21.9
    - pytest-asyncio >=0.19.0

about:
  home: https://github.com/d5h-foss/grpc-interceptor
  summary: Simplifies gRPC interceptors
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/d5h-foss/grpc-interceptor

extra:
  recipe-maintainers:
    - xylar
